# Generated by Django 5.1 on 2025-01-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='Nombre', default='Desconocido', max_length=100)),
                ('rubro', models.CharField(db_column='Rubro', max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(db_column='Nombre', default='Desconocido', max_length=100)),
                ('cargo', models.CharField(db_column='Cargo', max_length=100)),
                ('empresa', models.ForeignKey(db_column='EmpresaID', on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='sistema.empresa')),
            ],
            options={
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=100)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('trabajador', models.ForeignKey(db_column='TrabajadorID', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sistema.trabajador')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
    ]
